### ISSUE TITLE
[Not an issue] Requesting help about new LuaStateFiveThree()

### ISSUE THREAD

**Issue by IgorTimofeev** [MightyPirates/OC-JNLua#1]
Hello there. I'm writing an OC emulator and wanting to add architecture changing for virtual machines. The problem is when I'm loading **lua52**/native.64.dylib everything is just fine and just works perfectly with new **LuaState**(). But when i'm switching to **lua53**/native.64.dylib and creating a new **LuaStateFiveThree**() object, a strange error is occured. It seems like .dylib has been initialized, but something fails creation of LuaState:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: li.cil.repack.com.naef.jnlua.LuaState.lua_registryindex()I
	at li.cil.repack.com.naef.jnlua.LuaState.lua_registryindex(Native Method)
	at li.cil.repack.com.naef.jnlua.LuaState.<clinit>(LuaState.java:137)
	at com.company.Main.main(Main.java:13)
```

Here is code example. I'm out of any ideas of how to fix that - so any help would be really appreciated.

```java
package com.company;

import li.cil.repack.com.naef.jnlua.LuaState;
import li.cil.repack.com.naef.jnlua.LuaStateFiveThree;
import li.cil.repack.com.naef.jnlua.NativeSupport;

public class Main{
    public static void main(String[] a) {
        NativeSupport.getInstance().setLoader(() -> {
            System.load("/Users/igor/Desktop/lua53/native.64.dylib");
        });

        LuaState lua = new LuaStateFiveThree();
    }
}
```

**Comment by asiekierka** [comment]
`at li.cil.repack.com.naef.jnlua.LuaState.<clinit>(LuaState.java:137)`

Ah, the code is currently expecting both libraries to be loaded!
